### ISSUE TITLE
Access denied while trying to login using google while setting up the project

### ISSUE THREAD

**Issue by poswalsameer** [code100x/muzer#117]
Hi, I am trying to setup Muzer in my local development environment, but getting "Access denied" while logging in using my Google account. Am I missing something?

A help would be much appreciated!

Screenshot for reference:
![Screenshot (46)](https://github.com/user-attachments/assets/9be3aa78-8808-426b-9bea-df0e845d9440)

**Comment by Vishawdeep-Singh** [comment]
Looks like you didnt set up your google credentials correctly.

**Comment by SujithThirumalaisamy** [comment]
check you .env and the redirect url in the google api console
