### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by Ameerjafar** [code100x/muzer#118]
![Screenshot 2024-09-24 095401](https://github.com/user-attachments/assets/a271370f-1430-4a4d-b7c3-b976266b841c)
we have to go inside the next-app and run the pnpm install and also in the package.json  we should rewrite the command from prisma migrate to prisma migrate dev in the prisma:migrate object.

**Comment by Ameerjafar** [comment]
@SujithThirumalaisamy can you kindly check this one.

**Comment by SujithThirumalaisamy** [comment]
Nope, We have two different services. cd into `next-app` and `ws` and install the dependencies there. And start both the services
