### ISSUE TITLE
Songs not loading up on dashboard

### ISSUE THREAD

**Issue by Yash456k** [code100x/muzer#12]
When using the web interface, the songs don't load. They are temporarily added to the queue where its thumbnail doesnt seem to load as well.

### How to replicate :

Step 1: Log in
Step 2 : Go to the dashboard ( you are automatically redirected)
Step 3 : Try to load up any song from yt.
![image](https://github.com/user-attachments/assets/daaf243a-6137-47ef-b1a1-a41242475e58)

Step 4 : Click the "Add to Queue" button

![image](https://github.com/user-attachments/assets/b551a0f6-cf5b-459d-aab4-a0d371dcf43c)

Step 5 : wait for a few seconds. It does not queue up the song.

![image](https://github.com/user-attachments/assets/a28ba455-1874-4a1f-9d9b-ab980cdbec0a)

I'm new to this. Please inform me if this issue is redundant or irrelevant.

**Comment by RajuShivarama** [comment]
can i work on this issue

**Comment by IamAbhinavSINGH** [comment]
Hey, can I also work on the issue ?

**Comment by piyush1008** [comment]
the problem  is with the youtube-search-api , in the production env it is returning title and thumbnails undefined which is breaking the backend endpoint [/api/streams]
