### ISSUE TITLE
URL parsing issue in WS

### ISSUE THREAD

**Issue by SujithThirumalaisamy** [code100x/muzer#124]
The URL parsing logic in WS should be handled the same as we do in next-app with the REGEX

- Use the function `isValidYoutubeURL` and `getVideoId` to parse the videoId from all forms of youtube video urls
`utils.ts`
```javascript
export const YT_REGEX =
  /^(?:https?:\/\/)?(?:www\.)?(?:m\.)?(?:youtube\.com\/(?:watch\?(?!.*\blist=)(?:.*&)?v=|embed\/|v\/)|youtu\.be\/)([a-zA-Z0-9_-]{11})(?:[?&]\S+)?$/;

export const isValidYoutubeURL = (data: string) => {
  return data.match(YT_REGEX);
};

export const getVideoId = (url: string) => {
  return url.match(YT_REGEX)?.[1];
};

**Comment by geekyharsh05** [comment]
@SujithThirumalaisamy Can you please assign me?

**Comment by SujithThirumalaisamy** [comment]
@geekyharsh05 Can you add this?

**Comment by geekyharsh05** [comment]
Yeah, I am sick so will try to add it in 48 hours will it be fine?

**Comment by SujithThirumalaisamy** [comment]
Sure fine
