### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by SujithThirumalaisamy** [code100x/muzer#125]
<img width="718" alt="image" src="https://github.com/user-attachments/assets/da941030-3783-4bb0-843b-c11d83e2cf10">

## Redesign the card in the spaces
<img width="110" alt="image" src="https://github.com/user-attachments/assets/c5595237-1859-4ea1-a081-07bd1dc7a164">

## Missing padding in the spaces title

**Comment by geekyharsh05** [comment]
Can i take this?
