### ISSUE TITLE
Logout is not redirecting to /

### ISSUE THREAD

**Issue by user-64bit** [code100x/muzer#132]
Hello Hello :wave: 

Here in [video](https://www.awesomescreenshot.com/video/32047655?key=c966b0bbf5f7b12936f8cd2f1b6a8571) you can see when I click on `Logout` it does not redirect me to `/` page.

The issue is most probably coming from [this lines](https://github.com/code100x/muzer/blob/main/next-app/components/Appbar.tsx#L29C1-L32C17)

I think either using `async await` or adding `router.push('/')` should solve the issue.

**Comment by geekyharsh05** [comment]
@user-64bit It is working on both the landing page and the Spaces section page but in the dashboard i guess it is missing the `redirect: true`.

```bash
<button onClick={() => signOut({ callbackUrl: '/', redirect:true })}>
  Sign Out
</button>
```

Like this I guess?

@SujithThirumalaisamy Is it right?

**Comment by geekyharsh05** [comment]
@user-64bit It is working on both the landing page and the Spaces section page but in the dashboard i guess it is missing the `redirect: true`.

```bash
<button onClick={() => signOut({ callbackUrl: '/', redirect:true })}>
  Sign Out
</button>
```

Like this I guess?

@SujithThirumalaisamy Is it right?

**Comment by SujithThirumalaisamy** [comment]
The app isnt productionized with the latest code base yet. Will do it soon. Its already fixed in the current codebase. Nw
