### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by NalinDalal** [code100x/muzer#138]
Steps to reproduce:
1. Go to https://muzer.100xdevs.com/
2. Click on Get Started or Learn More
3. Nothing happens

**Comment by geekyharsh05** [comment]
@NalinDalal The maintainer of this repo hasn't deployed the latest codebase into thr prod. That's why it's not working.

**Comment by SujithThirumalaisamy** [comment]
The latest code is not in the production. Will push that soon. THankyou!
