### ISSUE TITLE
Fix: Toast should be configured

### ISSUE THREAD

**Issue by SujithThirumalaisamy** [code100x/muzer#21]
<img width="622" alt="image" src="https://github.com/user-attachments/assets/de413979-9e66-4ee5-a1b8-16da747abad0">

- Toast should be configured at a single place

**Comment by RajuShivarama** [comment]
sir, can i work on that

**Comment by SujithThirumalaisamy** [comment]
> sir, can i work on that

Sure

**Comment by RajuShivarama** [comment]
I have created the pull request, please kindly check it
