### ISSUE TITLE
While input box is empty than also add card. 

### ISSUE THREAD

**Issue by Vegadjay** [code100x/muzer#49]
![Screenshot from 2024-08-31 14-39-43](https://github.com/user-attachments/assets/9cd15c64-f570-41b9-962e-3f65407ce88b)
[Screencast from 2024-08-31 14-40-25.webm](https://github.com/user-attachments/assets/871bda9a-03dd-4602-9f6f-2e2b196907a3)

While input box is empty than also new video added and showing in new card that is not right so add validation for input box that improve  the UI and showing currectly

**Comment by 360Parminder** [comment]
it also showing same when i entered link and added to list. when i checked for response it showing "message":"Error while adding a stream" by  "https://muzer.100xdevs.com/api/streams"

**Comment by Vegadjay** [comment]
@hkirat review this pr #49

**Comment by Vegadjay** [comment]
@360Parminder Yes it's happening because pr is not merged
