### ISSUE TITLE
issue in production while adding the you tube link getting 500 error 

### ISSUE THREAD

**Issue by anuj-rishu** [code100x/muzer#75]

**Comment by Vegadjay** [comment]
@anuj-rishu Describe Your issue Proper

**Comment by anuj-rishu** [comment]
> @anuj-rishu Describe Your issue Properly
> 

When I am using the you tube Search api in local host then it song gets added,  and database is running fine. but when I am using in production , song is not adding in stream , upon opening the console it show 500 internal server error (for api/streams route ) , expect from this  rest of the things is working fine in production

**Comment by Vegadjay** [comment]
@anuj-rishu  That all problems are solved in diffrent issues so when pr merged than all problems are solved..

**Comment by Lakshya429** [comment]
what is the reason for this problem

**Comment by SujithThirumalaisamy** [comment]
Will be fixed in the new prod
