### ISSUE TITLE
Multistage dockerfile

### ISSUE THREAD

**Issue by SujithThirumalaisamy** [code100x/muzer#91]
Currently the next-app 's build image have a enormous size. Please add a multistage docker file to reduce the size

**Comment by geekyharsh05** [comment]
Can you please assign me?

**Comment by geekyharsh05** [comment]
@SujithThirumalaisamy For dev or prod?

**Comment by SujithThirumalaisamy** [comment]
prod

**Comment by geekyharsh05** [comment]
@SujithThirumalaisamy Ok
